services:
    
    telegram:
      build: ./services/telegram
      ports:
      - "8000:80"
    
    github:
        build: ./services/github
        ports:
        - "8001:80"

    airtable:
        build: ./services/airtable
        ports:
        - "8002:80"

    database:
        build: ./services/database
        ports:
        - "8003:80"
    